### ISSUE TITLE
Allow multiple answers in the same question

### ISSUE THREAD

**Issue by Bff2003** [KeepKindling/Pokemon-quiz#1]
The code doesn't prevent the multiple clicks and when the program increments the score it doesn't verify if the score is already in the max.

**Comment by KeepKindling** [comment]
What am I supposed to do with this information? I have already submitted
the project. And I have had no feedback for my first project

**Comment by Bff2003** [comment]
I'm just trying to help you, try this in your code, in the function for increment the score:
```JavaScript 
function incrementScore() {
    console.log('score + 1');
    integer += (integer > questions.length) ? 0 : 1; // to prevent integer from going over the length of the questions array
    displayScore();
}
```

and in the function `selectAnswer(e)` after the `clickedButton.classList.add(classToAdd)` try this:
```JavaScript 
  // disable all buttons to prevent multiple clicks
  answerBoxElement.childNodes.forEach(element => { 
      element.disabled = true;
  });
```
this will resolve these problems :)

**Comment by KeepKindling** [comment]
Okay sorry for abrupt reply. I'll give that a try and then commit the new
code.

**Comment by KeepKindling** [comment]
This solution worked. Thankyou for the help. This site is my second go at
project 2 as I decided to change ideas mid project so ran out of time to do
other things that the site would ideally do.

I apolagize again for being abrupt, I've been quite stressed out recently.

Do I need to do anything else?

**Comment by KeepKindling** [comment]
Why did you tell me to add the code even though I already submitted my Project?  Because I added code to it after submitting, I’m going to be given a fail so thanks for not helping me out at all!  Sent from Mail for Windows From: Bernardo FarrobinhaSent: 10 August 2022 12:44To: KeepKindling/Pokemon-quizCc: Andrew Curley; CommentSubject: Re: [KeepKindling/Pokemon-quiz] Allow multiple answers in the same question (Issue #1) I'm just trying to help you, try this in your code, in the function for increment the score:function incrementScore() {    console.log('score + 1');    integer += (integer > questions.length) ? 0 : 1; // to prevent integer from going over the length of the questions array    displayScore();}and in the function selectAnswer(e) after the clickedButton.classList.add(classToAdd) try this:  // disable all buttons to prevent multiple clicks  answerBoxElement.childNodes.forEach(element => {       element.disabled = true;  });this will resolve these problems :)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
